# Generated by Django 2.2.5 on 2019-10-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191015_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
